source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Devise authentification gem
gem "devise", "~> 4.8.1"
gem "devise-jwt", "~> 0.10.0"


# replace httpparty
gem "typhoeus", "~> 1.4.0"
gem "ethon", "~> 0.9.0"
gem "ffi", "~> 1.15.0"

# Omniauth
gem "omniauth"
gem "omniauth-twitter"
gem "omniauth-google-oauth2"

gem "google-api-client"
# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Rubocop
gem "rubocop-rails", "~> 2.15.2"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Simple, efficient background porcessing for Ruby
gem "sidekiq", "~> 6.5.7"
gem "sidekiq-scheduler", "~> 4.0.2"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# gem httparty to call api
gem "httparty", "~> 0.20.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Serializer
gem "active_model_serializers", "0.10.13"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors", "~> 1.1.1"

# Rswag gem for documentation
gem "rswag", "~> 2.7.0"
gem "rswag-api", "~> 2.7.0"
gem "rswag-ui", "~> 2.7.0"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "byebug", "~> 11.1.3"
  gem "rspec-rails", "~> 5.1.2"
  gem "rswag-specs", "~> 2.7.0"
  gem "factory_bot", "~> 6.2.1"
  gem "factory_bot_rails", "~> 6.2.0"
  gem "ffaker", "2.18"
  gem "annotate", "3.2.0"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
