#!/usr/bin/env python3

# from src.args import Arguments
from argparse import Namespace
from src.demography import demography
from src.args import parse_args, CountryCode
from typing import List


def entrypoint() -> int:
    args: List[CountryCode] = parse_args()
    demography(args)
    return 0


if __name__ == "__main__":
    exit(entrypoint())
