name: CashManager CI
on: push

env:
  MIRROR_URL: "git@github.com:EpitechMscProPromo2025/T-DEV-700-BDX_3.git"

jobs:
  clean_files:
    runs-on: ubuntu-latest
    steps:
      - name: Remove .DS_Store files
        run: find . -name '.DS_Store' -type f -delete
  push_to_mirror:
    needs: [clean_files]
    if: ${{ github.event_name == 'push' }} && ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
  DiscordNotification:
    runs-on: ubuntu-latest
    needs: [push_to_mirror]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1173647548574081146/Vo2SfNICTnLzn3TfMltJ7G4LOzYau883iCku2c8VLIKtzEzek9rY1uR2bWyRMjRNcNff
          DISCORD_USERNAME: Théau
          DISCORD_AVATAR: https://media.discordapp.net/attachments/487002983557627936/1173697654564327525/1659194713576.jpg
        uses: Ilshidur/action-discord@master
