name: Android Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build Android APK
        id: build
        working-directory: mobile/
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Build
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobile/app/build/outputs/apk/release/app-release.apk
          overwrite: true
