require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/widgets", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Widget. As you add validations to Widget, be sure to
  # adjust the attributes here as well.

  let(:valid_attributes) { attributes_for(:widget) }

  let(:valid_attributes_for_post) {
    {
      name: "Change Background",
      action:  { name: "at_hour",  options: {  hour: "18:00:00" } },
      reaction:  {  name: "daily_photo_bg",  options: {} }
    }
  }

  let(:invalid_attributes) {
    { name: 23, user_id: "a", active: true }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # WidgetsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Widget.create! valid_attributes
      get widgets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      widget = Widget.create! valid_attributes
      get widget_url(widget), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Widget" do
        login_as create(:user)
        expect {
          post widgets_url,
               params: { widget: valid_attributes_for_post }, headers: valid_headers, as: :json
        }.to change(Widget, :count).by(1)
      end

      it "renders a JSON response with the new widget" do
        login_as create(:user)
        post widgets_url,
             params: { widget: valid_attributes_for_post }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Widget" do
        expect {
          post widgets_url,
               params: { widget: invalid_attributes }, as: :json
        }.to change(Widget, :count).by(0)
      end

      it "renders a JSON response with errors for the new widget" do
        login_as create(:user)
        post widgets_url,
             params: { widget: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "New Name", active: true }
      }

      before { sign_in(create(:user)) }

      it "updates the requested widget" do
        widget = create(:widget_complet)
        patch widget_url(widget),
              params: { widget: new_attributes }, headers: valid_headers, as: :json
        widget.reload
        widget.name == "New Name"
      end

      it "renders a JSON response with the widget" do
        widget = create(:widget_complet)
        patch widget_url(widget),
              params: { widget: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    before { sign_in(create(:user)) }

    it "destroys the requested widget" do
      widget = Widget.create! valid_attributes
      expect {
        delete widget_url(widget), headers: valid_headers, as: :json
      }.to change(Widget, :count).by(-1)
    end
  end
end
