services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    volumes:
      - /home/mariadb_data:/var/lib/mysql

  web:
    image: dolibarr/dolibarr:latest
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: "http://0.0.0.0"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "admin"
      PHP_INI_DATE_TIMEZONE: "Europe/Paris"
    ports:
      - "80:80"
    links:
      - mariadb
    volumes:
      - /home/dolibarr_data:/var/www/documents
      - /home/dolibarr_custom:/var/www/html/custom
