---
- name: Install GPG
  tags: nodejs, install, setup
  become: true
  apt:
    name: gnupg
    update_cache: yes
    state: present

- name: Install the gpg key for nodejs LTS
  become: true
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: true
  changed_when: false
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install NodeJS
  tags: nodesjs, install
  become: true
  changed_when: false
  apt:
    name: nodejs
    state: latest

- name: Install NPM
  tags: npm, install
  become: true
  changed_when: false
  apt:
    name: npm
    state: latest