#!/usr/bin/env python3

from src.args import parse_args
from src.pacman import Pacman

def entrypoint() -> int:
    args = parse_args()
    pacman = Pacman(args)
    if not pacman.parse_file():
        return 84
    pacman.compute()
    pacman.print()
    return 0

if __name__ == "__main__":
    exit(entrypoint())