#!/usr/bin/env python3

from src.dannon import main
from src.args import parse_args


def entrypoint() -> int:
    args = parse_args()
    return main(args)


if __name__ == "__main__":
    exit(entrypoint())
