#!/usr/bin/env python3

from src.args import parse_args
from src.poll import poll


def entrypoint():
    args = parse_args()
    return poll(args)


if __name__ == "__main__":
    exit(entrypoint())
