#!/usr/bin/env python3

from src.args import parse_args
from src.pollution import main


def entrypoint() -> int:
    args = parse_args()
    return main(args)


if __name__ == "__main__":
    exit(entrypoint())
