/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Add the repository for jasync-sql
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Javalin
    implementation("io.javalin:javalin:5.6.3")

    // (Simple Logging Facade for Java) provides a Java logging API.
    implementation("org.slf4j:slf4j-simple:2.0.9")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Jackson
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.16.+")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

    // postgresql
    implementation("com.github.jasync-sql:jasync-postgresql:2.2.0")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClass.set("cashmanager.main.AppKt")
}
